//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSec.UserMaint {
    
    
    public partial class UM_HomePageSetup {
        
        /// <summary>
        /// UC_HomePageSetup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserSec.UM_UserControls.UM_UC_HomePageSetup UC_HomePageSetup;
    }
}
